@startuml

!include ClassDefs.iuml

header Scott Logic DataHelix Project
footer 15 February 2019
title Generate Class Hierarchy

GenerationConfigSource --|> ConfigSource

CommandLineBase <|-- GenerationCommandLine

CommandLineBase --|> ConfigSource
Runnable <|-- CommandLineBase

GenerateExecute --|> Runnable
GenerateExecute --* GenerationConfig
GenerateExecute --* ProfileReader
GenerateExecute --* GenerationEngine
GenerateExecute --* GenerationConfigSource
GenerateExecute --* OutputTarget
GenerateExecute --* GenerationConfigValidator
GenerateExecute --* ErrorReporter

GenerationConfigValidator --* OutputTarget
GenerationConfigValidator --* GenerationConfigSource


hide VisualiseExecute
hide VisualisationConfig
hide VisualisationConfigSource
hide VisualisationConfigValidator
hide StaticContradictionDecisionTreeValidator

@enduml
