@startuml

!include ClassDefs.iuml

header Scott Logic DataHelix Project
footer 15 February 2019
title Visualisation Class Hierarchy

ConfigSource <|-- VisualisationConfigSource
CommandLineBase <|-- VisualiseCommandLine

CommandLineBase --|> ConfigSource
Runnable <|-- CommandLineBase

VisualisationConfigValidator --* OutputTarget
VisualisationConfigValidator --* VisualisationConfigSource

VisualiseExecute --|> Runnable
VisualiseExecute --* VisualisationConfig
VisualiseExecute --* ProfileReader
VisualiseExecute --* VisualisationConfigSource
VisualiseExecute --* VisualisationConfigValidator
VisualiseExecute --* ErrorReporter


hide GenerateExecute
hide GenerationConfig
hide GenerationConfigSource
hide GenerationConfigValidator
hide StaticContradictionDecisionTreeValidator

@enduml
